<?php 

/**
 * ProcessWire General site settings module
 *
 * Allows to set global site settings 
 *
 * by Piotr Markiewicz (pmarki)
 *
 * ProcessWire 2.8.x (development), Copyright 2016 by Ryan Cramer
 * https://processwire.com
 *
 *
 */

class GeneralSettings extends Process implements Module, ConfigurableModule {

	public static function getModuleInfo() {
		return array(
			'title' => __('General site settings', __FILE__),
			'summary' => __('Module that stores global site settings', __FILE__),
			'version' => 121,
			'permanent' => false, 
			'autoload' => true,
			'icon' => 'sliders', 
			);
	}

	protected static $defaults = array(
			'global' => 'g_settings',
			'settings' => '{"0":{"api":"title","label":"Your site title","type":"Text","width":"100","description":"","select":""}}',
	);


	public function init() {

		//register wire 'global'
		if (isset($this->data['global'])) {
			$this->wire($this->data['global'], $this);
		}

		if (!isset($this->data['settings'])) {
			parent::init();
			return;
		}

		//set api as key with value as value
		//it makes it callable $settings->key
		$langData = array();
		$data = json_decode($this->data['settings'], true);
		foreach ($data as $key => $field) {
			if (!isset($field['api'])) continue;

			$value = (isset($field['value']) ? $field['value'] : '');
			if ($field['type'] == 'Textarea') {
				$value = nl2br($value);
			}

			if ($this->user->language) {
				//if api ends with language name: site_name_polish, add its value to langData array
				//so if user language is polish calling site_name will return its polish value
				if (strpos($field['api'], '_'.$this->user->language->name) !== false) {
					//$api without language suffix - site_title
					$api = str_replace('_'.$this->user->language->name, '', $field['api']);
					foreach ($data as $k => $f) {
						if ($f['api'] === $api) {
							$langData[$api] = $field['value'];
						}
					}
				}
			}
			$this->set($field['api'], $value);
		}
		foreach ($langData as $key => $value) {
			$this->set($key, $value);
		}
		parent::init();
	}

	/**
	 * Render all settings with basic markup
	 * 
	 * @return string markup
	 *
	 */
	public function render() {
		$out = '<p>';
		foreach (json_decode($this->data['settings'], true) as $key => $field) {
			if (isset($field['api']) && $field['type'] != 'Fieldset') {
				$v = (isset($field['value'])) ? $field['value'] : '';
				$out .= $this->wire('sanitizer')->entities($field['label'])
					. ' ('. $field['api'] . ') => ' 
					. nl2br($this->wire('sanitizer')->entities($v)) . '<br>';
			}
		}
		return $out .'</p>';
	}


	static public function getModuleConfigInputfields(array $data) {
		$data = array_merge(self::$defaults, $data);
		$options = array();
		$values = array();
		$json = (isset( $data['settings'] )) ? json_decode($data['settings'], true) : '';

		foreach ($json as $key => $value) {
			if ($value['type'] == 'Fieldset' || $value['type'] == 'FieldsetClose') {
				$options[$value['api']] ='-- '. $value['label'] . ' -- ' . $value['width'] . '%';
			} else {
				$options[$value['api']] = $value['label'] . ' ('. $value['api'] .') - ' . $value['width'] . '%';
			}
			$values[] = $value['api'];
		}

		$order = array();
        $fields = new InputfieldWrapper();
        $modules = wire('modules');

        //------------------------------------------
        $field = $modules->get("InputfieldMarkup");
        $field->label = __("Help", __FILE__);
        $help = ('<b>API variable</b> - Any combination of letters (a-z), numbers (0-9) and underscores (no spaces). 
        		You can call it in template files to output a value ($settings->site_name will return "My site").
        		<br>IMPORTANT: take care to not overload ProcessWire properties ($page, $user, etc.). It must be unique across all settings.<br>
        		<b>Label</b> - descriptive name for a backend user<br>
        		<b>Description</b> - longer explanation shown as notes in ProcessWire backend<br>
        		<b>Width</b> - field width in %, set between 10 and 100<br>
        		<b>Options for select or radios</b> - this will be used as names and labels, the best one word only');
        $field->entityEncodeText = false;
        $field->entityEncodeLabel = false;
        $field->attr('value', $help); 
        $field->collapsed = Inputfield::collapsedYes;
        $fields->append($field);

        //------------------------------------------
        $field = $modules->get("InputfieldText");
        $field->attr('name', 'global');
        $field->label = __("Global name", __FILE__);
        $field->attr('value', $data['global']); 
        $field->description = __('Use to call settings property in frontend ($settings->property).', __FILE__);
        $field->notes = __("After changing make sure to change it in your template files.", __FILE__);
        $field->collapsed = Inputfield::collapsedYes;
        $fields->append($field);

        //------------------------------------------
        $field = wire('modules')->get("InputfieldTextarea");
        $field->attr('name', 'settings');
        $field->attr('id', 'settings');
        $field->label = __("Json data", __FILE__);
        $field->attr('value', $data['settings']); 
        $field->columnWidth = 34;
        $field->collapsed = Inputfield::collapsedYes;
        $fields->append($field);

        //------------------------------------------
	   	$field = $modules->get("InputfieldAsmSelect");
        $field->attr('name', 'order');
        $field->attr('id', 'ASMOrder');
        $field->label = __("Settings", __FILE__);
        $field->addOptions($options);
        $field->attr('value', $values); 
        $fields->append($field);


        return $fields;
    }


}
